### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-reconcile#125]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate (alphabetically)
- [x] account_advanced_reconcile - #136
- [ ] account_advanced_reconcile_bank_statement
- [ ] account_advanced_reconcile_transaction_ref
- [ ] account_bank_statement_period_from_line_date
- [x] account_easy_reconcile @mdietrichc2c - #136
- [ ] account_invoice_reference
- [ ] account_payment_transaction_id
- [ ] account_reconcile_payment_order
- [ ] account_statement_bankaccount_completion
- [ ] account_statement_base_completion
- [ ] account_statement_base_import
- [ ] account_statement_cancel_line
- [ ] account_statement_commission
- [ ] account_statement_completion_label
- [ ] account_statement_completion_voucher
- [ ] account_statement_ext
- [ ] account_statement_ext_point_of_sale
- [ ] account_statement_ext_voucher
- [ ] account_statement_no_invoice_import
- [ ] account_statement_ofx_import
- [ ] account_statement_one_move
- [ ] account_statement_operation_multicompany
- [x] account_statement_operation_rule @cyrilgdn  #141
- [ ] account_statement_regex_account_completion
- [ ] account_statement_so_completion
- [ ] account_statement_transactionid_completion
- [ ] account_statement_transactionid_import
- [x] base_transaction_id @yvaucher https://github.com/OCA/bank-statement-reconcile/pull/127

**Comment by mdietrichc2c** [comment]
PR for the migration of both account_easy_reconcile and account_advanced_reconcile : https://github.com/OCA/bank-statement-reconcile/pull/136

**Comment by cyrilgdn** [comment]
PR for new V8 module account_statement_operation_rule: https://github.com/OCA/bank-statement-reconcile/pull/141

**Comment by yvaucher** [comment]
@cyrilgdn You are in the list. Thanks

**Comment by bodi000** [comment]
Hello,
I think I could use the module **account_statement_base_completion**, together with its localisation, l10n_ch_payment_slip_account_statement_base_completion. I see them both unported, so I would like to know if any effort has been already done for this migration, so I will not duplicate the work...

After a second look, I see it was not really ported since 7.0, and that there are a few PR which say they merge modules including this one. A bit lost all of a sudden : -)

Thank you in advance
B

**Comment by pedrobaeza** [comment]
So then there's any conclusion?
