### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-reconcile#156]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] ~~account_bank_statement_period_from_line_date~~ Not needed anymore
- [ ] account_invoice_reference
- [x] account_mass_reconcile - By @grindtildeath - #166 
- [ ] account_mass_reconcile_ref_deep_search - By @damdam-s - #208 
- [x] account_mass_reconcile_transaction_ref - ~~By @damdam-s - #207~~ By @grindtildeath - #222 
- [ ] account_move_bankaccount_import
- [ ] account_move_base_import - By @alexis-via - #164 
- [ ] account_move_so_import - By @damdam-s - #203 
- [ ] account_move_transactionid_import - By @damdam-s - #202 
- [ ] account_operation_rule
- [ ] account_payment_transaction_id
- [ ] account_reconcile_payment_order
- [ ] account_statement_cancel_line
- [ ] account_statement_completion_label
- [ ] account_statement_completion_voucher
- [ ] account_statement_ext
- [ ] account_statement_ext_point_of_sale
- [ ] account_statement_ext_voucher
- [ ] account_statement_no_invoice_import
- [ ] account_statement_one_move
- [ ] account_statement_operation_multicompany
- [ ] account_statement_regex_account_completion
- [ ] base_transaction_id - By @alexis-via - #164

**Comment by alexis-via** [comment]
PR #164

**Comment by grindtildeath** [comment]
Please add PR : https://github.com/OCA/bank-statement-reconcile/pull/166

**Comment by damdam-s** [comment]
@pedrobaeza  account_move_transactionid_import #202

**Comment by damdam-s** [comment]
@pedrobaeza account move so import  #203

**Comment by damdam-s** [comment]
@pedrobaeza account_mass_reconcile_transaction_ref #207

**Comment by damdam-s** [comment]
@pedrobaeza  account_mass_reconcile_ref_deep_search #208
