### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-reconcile#186]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_bank_statement_period_from_line_date
- [x] account_banking_reconciliation - By @murtuzasaleh - #261 
- [ ] account_invoice_reference
- [x] account_mass_reconcile - By @mpanarin - #197
- [x] account_mass_reconcile_by_purchase_line that is merged - By @jbeficent - #212
- [x] account_mass_reconcile_ref_deep_search - ~~By @sebalix - #229~~ By @grindtildeath - #232
- [x] account_mass_reconcile_transaction_ref - By @grindtildeath - #223 
- [ ] account_move_bankaccount_import
- [ ] account_move_base_import
- [ ] account_move_so_import
- [ ] account_move_transactionid_import
- [ ] account_operation_rule > account_reconcile_rule - By @grindtildeath - #209
- [ ] account_payment_transaction_id
- [ ] account_reconcile_payment_order
- [ ] account_statement_cancel_line
- [ ] account_statement_completion_label
- [ ] account_statement_completion_voucher
- [ ] account_statement_ext
- [ ] account_statement_ext_point_of_sale
- [ ] account_statement_ext_voucher
- [ ] account_statement_no_invoice_import
- [ ] account_statement_one_move
- [ ] account_statement_operation_multicompany
- [ ] account_statement_regex_account_completion
- [x] bank_statement_foreign_currency - By @jbeficent - #205
- [x] base_transaction_id - By @yvaucher - ~~#190~~ - #206

**Comment by grindtildeath** [comment]
@pedrobaeza Can you please update this for account_mass_reconcile_transaction_ref #222 (and close #207 )

**Comment by emagdalenaC2i** [comment]
Please check account_mass_reconcile because it is merged - By @mpanarin - #197 
Please add to the list account_mass_reconcile_by_purchase_line that is merged - By @jbeficent - #212 
Please add to the list bank_statement_foreign_currency - By @jbeficent - #205 
There are two PR to migrate account_mass_reconcile_ref_deep_search - By @sebalix - #229 and - By @grindtildeath - #232 
There is a PR to migrate account_operation_rule and rename to account_reconcile_rule - By @grindtildeath - #209

**Comment by Byloth** [comment]
Sorry, but...  
Module `base_transaction_id` is broken and has not been migrated properly.

You can find some extra details here: #237

**Comment by emagdalenaC2i** [comment]
> There are two PR to migrate account_mass_reconcile_ref_deep_search - By @sebalix - #229 and - By @grindtildeath - #232

@pedrobaeza #229 is closed and #232 is ready to be merged

It's not a big issue, but account_banking_reconciliation (# 174) by @ursais should keep the format: account_banking_reconciliation- By @ursais - #174
