### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-reconcile#497]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] account_mass_reconcile - By @sonhd91 - #517
- [x] account_move_reconcile_forbid_cancel - By @ACheung-FactorLibre - #568
- [x] account_move_reconcile_helper - By @mpascuall - #771
- [x] account_partner_reconcile - By @yibudak - #791
- [ ] account_reconcile_restrict_partner_mismatch - By @sbejaoui - #596
- [ ] account_reconciliation_widget
- [x] bank_statement_check_number - By @AlexPForgeFlow - #573

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by TeoGoddet** [comment]
Regarding account_reconciliation_widget, it seems a lot of works need to be done. 
Maybe a full refactoring using the new backend functions and owl would be better.
The entreprise module switched to more standard views (Heavily customized kanban) 
Would be awesome if we could have the chatter in the widget

**Comment by pedrobaeza** [comment]
Although that refactoring would be good, an initial step should be to adapt existing one for the few missing pieces in v16. The old JS engine is still there, so only bridges or little things like m2o widget should be needed, but not indepth analysis by my part yet.

The rest can come after this as a 2.0 version.

**Comment by sonhd91** [comment]
Please add module `account_mass_reconcile` into module list
`account_mass_reconcile`: https://github.com/OCA/account-reconcile/pull/517

**Comment by sonhd91** [comment]
`account_payment_mode_auto_reconcile` : #537

**Comment by DMopen2s** [comment]
My company is in the process of implementing Odoo v16 community, and we need your help in migrating the account_reconciliation_widget module from v15 to v16, we have an economic budget for the developer to help us in this work, and the module would be released in the community version 16, please if there is someone who can help us, I would greatly appreciate it.
Greetings.

**Comment by pedrobaeza** [comment]
Check #500 for the great replacement.

**Comment by DMopen2s** [comment]
Thank you very much @pedrobaeza, I will review and if I can contribute something, I will inform you.

**Comment by rrebollo** [comment]
@sbidoul I'm taking account_bank_statement_reopen_skip_undo_reconciliation at #737

**Comment by mpascuall** [comment]
Migrating account_move_reconcile_helper: https://github.com/OCA/account-reconcile/pull/771
